apiVersion: v1
kind: ConfigMap
metadata:
  name: share-webui-config
  namespace: default
data:
  REACT_APP_API_URL: "/api"
  NODE_ENV: "production"
  MONGO_URI: "mongodb://mongodb:27017/diffCheckerDB"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: share-webui-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: share-webui-frontend
  template:
    metadata:
      labels:
        app: share-webui-frontend
    spec:
      initContainers:
      - name: git-clone
        image: alpine/git
        command: ['sh', '-c']
        args:
          - |
            git clone https://github.com/vaibhav-r-pandey/regmap-genai.git /tmp/repo
            cp -r /tmp/repo/share_webui/* /app/
        volumeMounts:
        - name: app-source
          mountPath: /app
      containers:
      - name: frontend
        image: node:18-alpine
        workingDir: /app
        command: ['sh', '-c']
        args:
          - |
            npm ci
            npm run build
            npm install -g serve
            serve -s build -l 3000
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: share-webui-config
        volumeMounts:
        - name: app-source
          mountPath: /app
      volumes:
      - name: app-source
        emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: share-webui-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: share-webui-backend
  template:
    metadata:
      labels:
        app: share-webui-backend
    spec:
      initContainers:
      - name: git-clone
        image: alpine/git
        command: ['sh', '-c']
        args:
          - |
            git clone https://github.com/vaibhav-r-pandey/regmap-genai.git /tmp/repo
            cp -r /tmp/repo/share_webui/backend/* /app/
        volumeMounts:
        - name: app-source
          mountPath: /app
      containers:
      - name: backend
        image: node:18-alpine
        workingDir: /app
        command: ['sh', '-c']
        args:
          - |
            npm ci
            npm start
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: share-webui-config
        volumeMounts:
        - name: app-source
          mountPath: /app
      volumes:
      - name: app-source
        emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:6.0
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: share-webui-frontend
  namespace: default
spec:
  selector:
    app: share-webui-frontend
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: share-webui-backend
  namespace: default
spec:
  selector:
    app: share-webui-backend
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: default
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017