apiVersion: apps/v1
kind: Deployment
metadata:
  name: share-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: share-webui
  template:
    metadata:
      labels:
        app: share-webui
    spec:
      containers:
      - name: app
        image: node:18-alpine
        command: ['sh', '-c']
        args:
          - |
            apk add --no-cache git
            git clone https://github.com/vaibhav-r-pandey/regmap-genai.git /tmp/repo
            cd /tmp/repo/share_webui
            npm ci
            npm run build
            npm install -g serve
            serve -s build -l 3000 &
            cd backend
            npm ci
            npm start
        ports:
        - containerPort: 3000
        - containerPort: 5000
        env:
        - name: REACT_APP_API_URL
          value: "/api"
        - name: NODE_ENV
          value: "production"
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/diffCheckerDB"
      - name: mongodb
        image: mongo:6.0
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: share-webui-service
spec:
  selector:
    app: share-webui
  ports:
  - name: frontend
    port: 3000
    targetPort: 3000
  - name: backend
    port: 5000
    targetPort: 5000
  type: LoadBalancer