apiVersion: v1
kind: Service
metadata:
  name: share-webui-service
spec:
  selector:
    app: share-webui
  ports:
  - name: frontend
    port: 80
    targetPort: 3000
  - name: backend
    port: 5000
    targetPort: 5000
  - name: mongodb
    port: 27017
    targetPort: 27017
  type: LoadBalancer